/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1167826e0d5862e22a46b0be406899f1)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	DATABASE_URL: string;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	JWT_PRIVATE_JWK: string;
	JWT_KID: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DATABASE_URL" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "JWT_PRIVATE_JWK" | "JWT_KID">> {}
}
